# Site settings
title: TetCon
email: thai@tetcon.org
description: "TetCon provides attendees with hands-on experiences, cutting edge
              researches, and latest developments in information security in
              Vietnam and worldwide. Being the only vendor-neutral and the most
              technical conference in Vietnam, TetCon has become the premier
              information security event of the country. It has received many
              positive coverages by the local press and media and the
              participants of many of the world’s foremost information security
              experts. Only in its third year, TetCon has been widely recognised
              as the provider of the highest quality information security content,
              and the best place to connect with information security professionals
              in Vietnam."

baseurl: ""
url: "https://tetcon.org"
facebook_username: TetCon
twitter_username: TetCon

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Active conference setting
active_conference:
  name: Saigon 2015
  date: 6 January 2015
  location: Hotel Majestic Saigon
  ticket_url: http://ticketbox.vn/event/tetcon-saigon-2015-14509
  cfp_url: https://docs.google.com/forms/d/1bXFG9kmaMcT5mAGRImB1S9D6seoR7IsB5_4ki4Loo78/viewform?usp=send_form

collections:
  saigon-2015:
    name: Saigon 2015
    date: 6 January 2015
    location: Hotel Majestic Saigon
    output: true
  saigon-2013:
    name: Saigon 2013
    date: 15 January 2013
    location: HCMC University of Technology
    output: true
  saigon-2012:
    name: Saigon 2012
    date: 13 January 2012
    location: Trung Tâm Thông tin Hợp tác Quốc Tế Thông Tấn
    output: true